stages:
  - test
  - build&deploy


unit-test:
  script: C:\"Program Files"\Unity\Hub\Editor\2019.2.17f1\Editor\Unity.exe -batchmode -projectPath . -runTests -testPlatform editmode -logFile -testResults .\unit-tests.xml -quit
  stage: test
  tags:
    - unity

win-deploy:
  script:
   - C:\"Program Files"\Unity\Hub\Editor\2019.2.17f1\Editor\Unity.exe -batchmode -projectPath ./StealthGame -buildWindowsPlayer ToDeploy\build.exe -logFile logfile.xml -quit
  after_script: 
   - C:\Butler\butler.exe push ./StealthGame/ToDeploy eaglebyte/stealthgame:windows-32-beta   
  stage: build&deploy
  tags:
    - unity
    
mac-deploy:
  script:   
   - C:\"Program Files"\Unity\Hub\Editor\2019.2.17f1\Editor\Unity.exe -batchmode -projectPath ./StealthGame -buildOSXPlayer  ToDeploy\build.app -logFile logfile.xml -quit
  after_script: 
   - C:\Butler\butler.exe push ./ToDeploy eaglebyte/stealthgame:mac-32-beta 
  stage: build&deploy
  tags:
    - unity
    
