stages:
  - test
  - build
  - deploy

unit-test:
  script: C:\"Program Files"\Unity\Hub\Editor\2019.2.17f1\Editor\Unity.exe -batchmode -projectPath . -runTests -testPlatform editmode -logFile -testResults .\unit-tests.xml -quit
  stage: test
  tags:
    - unity

unity-build:
  script:
   - C:\"Program Files"\Unity\Hub\Editor\2019.2.17f1\Editor\Unity.exe -batchmode -projectPath ./StealthGame -buildWindowsPlayer ToDeploy\build.exe -logFile logfile.xml -quit
  stage: build
  tags:
    - unity

itchio:
  script:
   - butler -V
   - C:\"Program Files"\Unity\Hub\Editor\2019.2.17f1\Editor\Unity.exe -batchmode -projectPath ./StealthGame -buildWindowsPlayer ToDeploy\build.exe -logFile logfile.xml -quit  
   - butler push ./StealthGame/ToDeploy eaglebyte/stealthgame:windows-32-beta
  stage: deploy
  tags:
    - unity