stages:
  - test
  - build
  - deploy
  
  unit-test:
  stage: test
  script: "C:\Program Files\Unity\Hub\Editor\2019.2.17f1\Editor\
    -batchmode \
    -projectPath . \
    -runTests -testPlatform editmode \
    -logFile \
    -testResults ./unit-tests.xml"
  tags:
    - unity
  
  unity-build:
  stage: build
  script: echo 'Building...'
  tags:
    - unity
  
  playstore:
  stage: deploy
  script: echo 'Deploying...'
  tags:
    - unity