stages:
  - test
  - build
  - deploy

unit-test:
  script: C:\"Program Files"\Unity\Hub\Editor\2019.2.17f1\Editor\Unity.exe -batchmode -projectPath . -runTests -testPlatform editmode -logFile -testResults .\unit-tests.xml -quit
  stage: test
  tags:
    - unity

unity-build:
  script: C:\"Program Files"\Unity\Hub\Editor\2019.2.17f1\Editor\Unity.exe -batchmode -buildWindowsPlayer ToDeploy\build.exe -logFile .\logfile.xml -quit
  stage: build
  tags:
    - unity

itchio:
  script: "echo 'Deploying...'"
  stage: deploy
  tags:
    - unity